package com.fileupload.model;

public class FileUpload {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEUPLOAD.FID
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    private Short fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEUPLOAD.DETAIL
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    private String detail;

    private String title;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEUPLOAD.FID
     *
     * @return the value of T_FILEUPLOAD.FID
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    public Short getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEUPLOAD.FID
     *
     * @param fid the value for T_FILEUPLOAD.FID
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    public void setFid(Short fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEUPLOAD.DETAIL
     *
     * @return the value of T_FILEUPLOAD.DETAIL
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEUPLOAD.DETAIL
     *
     * @param detail the value for T_FILEUPLOAD.DETAIL
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }


	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	
    
    
}