package com.fileupload.dao;

import java.util.List;

import com.fileupload.model.FileUpload;

public interface FileUploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILEUPLOAD
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    int deleteByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILEUPLOAD
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    int insert(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILEUPLOAD
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    int insertSelective(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILEUPLOAD
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    FileUpload selectByPrimaryKey(Short fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILEUPLOAD
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    int updateByPrimaryKeySelective(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILEUPLOAD
     *
     * @mbggenerated Thu Feb 08 09:49:42 CST 2018
     */
    int updateByPrimaryKey(FileUpload record);
    /**
     * 查询所有数据
     * @return
     */
	List<FileUpload> selectByAll();
	/**
	 * 查询最后添加的那条数据
	 * @return
	 */
	FileUpload selectByMaxId();
}